from crewai import Task
from textwrap import dedent
from datetime import date
import os
from langchain_openai import ChatOpenAI

class Tasks():

  def set_up_research(self, agent, company, url):
    return Task(description=f"""
        Investigate what {company} is all about. This means that you
        describe its activities, but also assess its overall position in its industry and value chain.
        You make sure to use find all the necessary information to describe the company, its role in the value chain, the profile of its customers, its target audience, product and services range.
        It has to be an comprehensive and accurate report that encompases all the key aspects of the company.
        {self.__tip_section()}""",
      expected_output=f"""A concise report about {company}. The report should include:
      **1.** {company} description.
      **2.** The key problems {company} is trying to solve with its products and services
      **3.** The description and benefits of each of its product range and services
      **4** An overview of its product range and categories
      **5** An overview of its customer segments based on the customer information, testimonials, but also given the product range
      **6** The industry and sub-industry {company} is in, and the main competitors
      **7** The position of the {company} in the value chain of its industry and its split between B2B and B2C segments
      **8** The regions the company is operating
      **9** The main distribution channels, and the main marketing channels it is using
      **10** The existing relationships with financial institutions such as banks, investors, etc.
      **11** The main customer segments, and the main customer needs, their applications, and use cases
      **12** The {company} positioning based on pricing, messaging and product range
      The aim of this report is to provide everything that the next agents will need to understand {company} and its industry later on.
      You stop once you've considered that your content is valuable enough.""",
      async_execution=True,
      agent=agent,
      output_file=f"{os.getcwd()}/outputs/{date.today()}_set_up_research_{company}.txt")


  def quality_setup_assurance_review(self, agent, company, url):
    return Task(description=f"""
        Review the response drafted by the Senior Company Analyst about {company}. Ensure it is comprehensive, relevant, accurate, and actionable.
        Make sure to verify the information provided and ensure that no assumptions are made. Provide feedback to the senior company analyst on the
        quality of the response, ensuring it will contain all the key information to understand {company}.
        {self.__tip_section()}""",
        async_execution=True,
        expected_output=f"""A final, concise, timely, and actionable reports that defines {company}.""",
        agent=agent)
  
  def industry_research(self, agent, company, url, context):
    return Task(description=f"""
        Given everything you know about {company} and the report generated by the the Senior Company Analyst, you can thoroughly analyse the industry in which {company} is operating. You want to combine both hard data but also overall trends supporting it.
        Make sure all of your analysis is backed with data, evidence. You make no assumptions.
        {self.__tip_section()}""",
        context=context,
        async_execution=True,
        expected_output=f"""All of the report generated earlier, and you will add another section to the report that includes everything there is to know about the industry in which {company} is operating. You ensure everything information is only based on data and evidence but also applies to the country and possibly region in which {company} is operating.
        **1.** The country, and region in which {company} is operating.
        **2.** The market dynamics, including the headwinds, tailwinds, opportunities, risks of the industry
        **3.** The global trends that are impacting the industry
        **4.** The growth rates, measured in CAGRs, and the market size of the industry in the given country and region.""",
        agent=agent,
        output_file=f"{os.getcwd()}/outputs/{date.today()}_industry_research_{company}.txt")

  
  def economic_research(self, agent, company, url, context):
    return Task(description=f"""
        Given everything you know about {company} and the report generated by the the Senior Company Analyst, you can thoroughly benchmark the unit economics of the industry in which {company} is operating. You want to combine both hard data but also overall trends supporting it.
        Make sure all of your analysis is backed with data, evidence. You make no assumptions.
        {self.__tip_section()}""",
        context=context,
        async_execution=True,
        expected_output=f"""All of the report generated earlier, and you will add another section to the report that includes everything there is to know about the economics of competitors and players similar to {company}.
        You ensure every information is only based on data and evidence but also applies to the country and possibly region in which {company} is operating. You are always coming up with key metrics that can be used to benchmark companies across the industry. These metrics include:
        **1.** The key financial indicators such as gross margins, net margins, EBITDA margins, and operating margins
        **2.** Unit economics such as average order value for similar customers, cost to acquire a new customer, lifetime value of a customer, customer churn rates
        **3.** The major cost drivers in percentage of revenue. The the biggest source of expenses
        **4.** The main revenue streams and split across categories, applications, segments.
        **5.** The main levers used by players in the industry to boost revenues, reduce costs, and increase profitability. This can inluce services, products, pricing, marketing, sales, etc.
        """,
        agent=agent,
        output_file=f"{os.getcwd()}/outputs/{date.today()}_economic_research_{company}.txt")
  
  def customer_research(self, agent, company, url, context):
    return Task(description=f"""
        Given everything you know about {company} and the report generated by the the Senior Company Analyst, you can thoroughly evaluate the quality, health, relationship between {company} and its customers. You want to combine both hard data but also overall trends supporting it.
        Make sure all of your analysis is backed with data, evidence. You make no assumptions.
        {self.__tip_section()}""",
        context=context,
        async_execution=True,
        expected_output=f"""Yill will create another section to the report that includes everything there is to know about the customers of {company} and their relationship. 
        You ensure every information is only based on data and evidence but also applies to the country and possibly region in which {company} is operating. You are always coming up with key metrics that can be used to benchmark companies across the industry. These metrics include:
        **1.** The user persona of the main customer segments. Split between B2B and B2C segments.
        **2.** The main customer needs, their applications, and use cases
        **3.** The decision making process of the main customer segments
        **4.** The role, influence of the main customer segments on {company} and the industry
        **5.** The fragmentation of the customer base for {company}. Only mention if you're able to identify it.
        **6** The role of {company}'s products and services on the value chain and its customers.
        **7** The impact of the {company}'s contract value on the cost structures of its customers. This means that you research customers and understand how much the cost of this contract represents in their overall cost structure.
        **8.** The major events that could lead a B2B or B2B customer to upsell, contract, churn, default, or switch to a competitor of {company}. Split between B2B and B2C segments.
        **9.** The major tailwinds and opportunities impacting the customers of {company} and its competitors.
        """,
        agent=agent,
        output_file=f"{os.getcwd()}/outputs/{date.today()}_customer_research_{company}.txt")

  def financial_research(self, agent, company, url, context):
    return Task(description=f"""
        Given everything you know about {company} and the report generated by the the Senior Company Analyst, you can thoroughly evaluate the investment dynamics happening in the industry and country of {company}. The goal is to spot if potential strategic acquirers and financial investors are interested in the space.
        Make sure all of your analysis is backed with data, evidence. You make no assumptions.
        {self.__tip_section()}""",
        context=context,
        async_execution=True,
        expected_output=f"""You will will create another section to the report that includes everything there is to know about the past M&A transactions, mergers, bankruptcies in the industry of {company} in its relevant country.
        You ensure every information is only based on data and evidence but also applies to the country and possibly region in which {company} is operating.
        You are always coming up with accurate, timely information. This means that you research activities that date from the years 2022, 2023, 2024. Not ear with key metrics that can be used to benchmark companies across the industry. These metrics include:
        **1.** The recent mergers and acquisitions in the industry of {company}. Be hyper specific and focus only on the country in which {company} is operating. Mention the deals that have been made, and the companies involved.
        **2.** The names of the most actives investors and the most recent transactions they completed in that space. Focus on deals of similar sizes to the {company}.
        **3.** If possible, find multiples, metrics regarding the acquisitions, such as acquisition value, EBITDA multiples, and the reasons why these investors are interested in the space.
        **4.** If possible, find the reasons that could make it interesting for investors and strategic acquirers to invest in this space. This can range from wanting to consolidate, to expanding into new regions, adding new products, tapping into new segments, etc.
        **5.** The tailwinds and headwings justifying the investments or divestments in the industry of {company}.        **6** The role of {company}'s products and services on the value chain and its customers.
        """,
        agent=agent,
        output_file=f"{os.getcwd()}/outputs/{date.today()}_financial_research_{company}.txt")

  def report_quality_assurance(self, agent, company, url, context):
    return Task(description=f"""
        Given all the information you're being provided by the other agents about {company}, you always keep them accountable to ensure they deliver outstanding work. 
        You ensure that the reports are comprehensive, relevant, accurate, and actionable. You provide feedback to the agents on the quality of the response, ensuring it will contain all the key information to understand {company}.
        You make sure all of their analysis is backed with data, evidence and that they make no assumptions.
        {self.__tip_section()}""",
        context=context,
        async_execution=True,
        expected_output=f"""You
        """,
        agent=agent,
        output_file=f"{os.getcwd()}/outputs/{date.today()}_financial_research_{company}.txt")

  def __tip_section(self):
    return "If you do your BEST WORK, I'll tip you $10000! and you will get promoted to the next level!"